### PR TITLE
Add play_media service

### PR DESCRIPTION
**Pull request by dgomes**
This implements the `media_play` service which enables programatic channel change

### CODE REVIEW

**Comment by dgomes** [comment]
IMHO this feature still makes sense

**Comment by dgomes** [comment]
not stale 😀

**Comment by nao-pon** [comment]
👍

**Comment by dgomes** [comment]
:(

**Comment by dgomes** [comment]
😢

**Comment by dgomes** [comment]
Such a shame....

**Comment by vassilis-panos** [comment]
I will not comment on whether it is a shame or not.
So does this pull request only work if the source keys are "Channel {integer}"?

**Comment by dgomes** [comment]
Thank you for replying :)

The all point of the PR is support for changing directly to TV channels >9 which require pressing more than 1 key without any need for external scripts/automations.

The PR just de-multiplexes a large `Channel` (unsupported) into the composing `Channel` keys (e.g. Channel 51 -> Channel 5 + Channel 1)

**Comment by vassilis-panos** [comment]
That's why I did not accept this PR. Because it only solves your problem and dictates the name of the sources .
An ideal implementation of play_media service is to try to find and map the correct source key, either the media_id is number or string, so you can change channels from voice controllers. For example Alexa, switch to HDMI or Alexa, tune to Fox. 
We also need to take into account that we have an “overriding source names” function.
 https://github.com/smartHomeHub/SmartIR/blob/master/docs/MEDIA_PLAYER.md#overriding-source-names

**Comment by dgomes** [comment]
Thank you for your feedback.

I don't think this is only my problem, as I've seen complicated automations to change channels... 

MEDIA_TYPE_CHANNEL is supposed to be used for channels only (not sources), channels can have numbers or names (have a look into existing media_players). 

If you look into official media_players such as `samsungtv` and `mediaroom` you see that the same pattern I followed (only numbers) this is because that is the only thing the underlying platform actually supports (IR blasters don't expose channel names). 

If really necessary I can create an `overriding channel names` feature:

```yaml
    channel_names:
      Channel 51: BBC
      Channel 12: RTL
      Channel 1: RAI
```

**Comment by vassilis-panos** [comment]
In my opinion, WebOS TV has the right implementation of play_media service.
Ok, I’m going to merge it. It would be great if you could document on how it works.

**Comment by dgomes** [comment]
Thanks 🎉

**Comment by Dilbert66** [comment]
Glad it was finally added. I had a pull request for similar functionality a while back and there was no response on it so I forked my own version.  
https://github.com/smartHomeHub/SmartIR/pull/240

**Pull request merged**
