### PR TITLE
Fix ir code

### PR DESCRIPTION
**Pull request by keitetran**
From #4 and #1  i want fix it for my AC. It was tested on my AC. You can remove not use code.

### CODE REVIEW

**Comment by smartHomeHub** [comment]
How did you get the commands? Did you set the mode, turn your unit off and then on for each command?

**Comment by keitetran** [comment]
Yeah. I set mode, temp and wind, then turn off -> learn ON command with same state. 
Loop it for all command.

**Comment by smartHomeHub** [comment]
Oh man, you are a hero. I'll merge it later today

**Comment by keitetran** [comment]
Like for your component.

**Pull request merged**
