### PR TITLE
Add MQTT controller support

### PR DESCRIPTION
**Pull request by forfuncsake**
This commit adds support for an MQTT-based controller to be used with the climate component.

A user would need to have an appropriate MQTT client that can emit IR/RF/etc based on the
payload received.

There is some prior discussion in #49 which should be resolved prior to this PR merging.

### CODE REVIEW

**Comment by 2016for** [comment]
Hey I am mid-way through setting my DIY ESP8266 mqtt IR remote. I have an IR receiver on it, are you able to change state in Home assistant via mqtt state topic or something?

As in I want the IR receiver to sync HA mode/temp/fan speed if someone uses a manual remote.

There should be a way, mqtt supports command topic and state topic so should be possible right?

**Comment by forfuncsake** [comment]
SmartIR doesn't currently support getting state from MQTT (only sending commands).
What you want to do it possible, with some caveats.

You could set up a standard mqtt sensor and an HA automation that decodes the state message your IR receiver has published to the topic. The automation could then apply those changes to the climate service. The main caveat here is that the climate service (using SmartIR) would then echo the same command back to the command topic and your IR emitter would send it on to the AC unit. This is not a huge problem, your AC may accept the command and "beep", but it should just be the same command again and shouldn't throw anything out of whack.

**Comment by 2016for** [comment]
Thanks for the prompt reply @forfuncsake 

While researching I just found that there's a HA climate mqtt platform as well, which takes care of all this.

Trying to figure out if using that would be a better idea. I mean if commands are being sent via mqtt, then what are the advantages of using smartir and not climate mqtt?

Thanks again for the inputs.

**Comment by smartHomeHub** [comment]
Indeed, using the official mqtt component is a better idea. The SmartIR difference is that it sends the full command in a single topic (temperature, fan etc).

**Comment by 2016for** [comment]
ah nice. Thanks for the clarification.

I am using IRRemoteESP8266 Library (which I think works with different commands for each) so should be ok.

@smartHomeHub Just one more question, IRRemoteESP8266 library has my specific Fujitsu remote in it, is there a way I could extract codes from there to use with my Broadlink  and smartIR?

**Pull request merged**
