### PR TITLE
add presets to climate

### PR DESCRIPTION
**Pull request by Zen3515**
The main change is in climate.py where I added preset support.

To use preset you must add key `"presets"` into code.json, if the old code without `"presets"` key were use, it'll work like normal.

```json
"presets": ["none", "eco"],
````

Then inside `"commands"` key, you must add the mode beside none here before operation mode.

```json
"commands": {
    "off": "...",
    "cool--operation-mode-cool-when-preset-none": {
        "auto": {},
        "low": {},
    },
    "eco--presets-eco": {
        "cool--operation-mode-cool-when-preset-eco": {
            "auto": {},
            "low": {},
        },
    }
}
```
Ignore from `--` I added that to add a comment.

You can look at the finished new code file at another pull request from me that edit `1162.json`

I use home assistant dev container to edit the code, it just formats the file that I press save.
If you want me to just add the change, I'm willing to help.

### CODE REVIEW

**Comment by Zen3515** [comment]
You might wanted to look at json from https://github.com/smartHomeHub/SmartIR/pull/710

**Comment by vassilis-panos** [comment]
I'm on summer vacation right now. It is an interesting approach.

**Comment by Zen3515** [comment]
@vassilis-panos I've updated to the current version with master. Would you merge this branch? what do you want me to do next?

**Comment by Zen3515** [comment]
@vassilis-panos would you like to revive this PR?

**Pull request closed without merging**
