### PR TITLE
dry, fan_only and auto modes

### PR DESCRIPTION
**Pull request by drew-kun**
Added codes for dry, fan_only and auto modes for all 4 fan speeds (fanModes).
As at least on Gree GWH12-KF-K3DNA5G-I (tested - all works perfectly on this model) auto mode uses it's own logic to determine comfortable temperature setting, there are only 4 different codes used for this auto mode (each for the corresponding fan speed (fanMode) value)

### CODE REVIEW

**Comment by drew-kun** [comment]
Please, let me know if you think I do anything wrong.

**Comment by drew-kun** [comment]
Wtf?

**Comment by smartHomeHub** [comment]
Sorry but we don't accept partial device files. Please remove the cool section and also rename 'auto' operation mode to 'heat_cool'.

**Comment by drew-kun** [comment]
Sorry, could you please explain what do you mean by 'partial device files'? I think, I have made it pretty solid. Also why would you like me to remove the 'cool' section? Thanks

**Pull request closed without merging**
