### PR TITLE
Add support for LG InverterV P12RK

### PR DESCRIPTION
**Pull request by fontanellif**
Add support for LG InverterV P12RK.

Let me know if i have to change de ID (9999).

### CODE REVIEW

**Comment by smartHomeHub** [comment]
Hello and thank you for your support.
What about auto-> level 2 and 3?

**Comment by fontanellif** [comment]
Hello, 
i commit the mid&high configuration of auto mode.

By the way: 

1) the regular name of LG for the auto mode is "Artificial intelligence"
2) the dry option for this model don't support the temperature option. In this case i can set the mode but i cant set the temperature. So i use , as workaround, the same code for all temperature of the dry mode.

**Comment by smartHomeHub** [comment]
Amazing. I really appreciate your help

**Comment by fontanellif** [comment]
And i really appreciate your work with this component!!

**Pull request merged**
