### PR TITLE
add codes for Toshiba RAS-B07(10/13) J2KVSG-E

### LINKED ISSUE #689: Add Toshiba RAS-B07(10/13) J2KVSG-E air conditioning
Toshiba RAS-B07(10/13) J2KVSG-E codes are missing. 
**Home Assistant version**
2021.7.4

**SmartIR version**
current master, commit 4fe2f7cb12e35979715354a207fc976393d61bef

**SmartIR configuration**

```yaml
climate:
  - platform: smartir
    name: "Living room"
    unique_id: living_room
    device_code: 1260 
    controller_data: remote.remote2_remote
```

**Describe the bug**

Unfortunatly, no of the other codes for toshiba AC units seem to work with RAS-B07(10/13) J2KVSG-E.

### PR DESCRIPTION
**Pull request by gador**
Fixes #689 

Noteworthy things:
Toshiba allows for a handful more features (like power selection of outdoor AC unit, ECO mode, air flow direction of HDA air stream). 
These are not reflected here and cannot (easily) be reflected by the climate integration in home-assistant. 

Also the `dry` mode can only work with `auto` fan setting.

### CODE REVIEW

**Comment by gador** [comment]
may I ask why the PR hasn't been merged?

**Comment by gador** [comment]
@vassilis-panos ,
again, may I ask, why you do not merge this PR? Is there something I can do?
Thanks

**Comment by vassilis-panos** [comment]
Hi and sorry for the delay.
You need to fill missing dry and fan_only modes
If they do not exist you will have to repeat them

**Comment by gador** [comment]
hi @vassilis-panos ,
thanks for the reply. The dry mode and fan_only mode can be found in lines 324ff and 341ff respectively.

**Pull request merged**
