### PR TITLE
Add support for a delay between commands

### PR DESCRIPTION
**Pull request by bdraco**
I was getting dropped temperature changes if commands were sent too quickly.

My Aircon needs a delay beween sending commands in order for it to be reliable.

### CODE REVIEW

**Comment by nagyrobi** [comment]
+1 for this

**Comment by bdraco** [comment]
Not stale￼

**Comment by bdraco** [comment]
I'll rebase this when I get back to the location with the device in early Nov

**Comment by bdraco** [comment]
@vassilis-panos Any hint why this was closed?

**Pull request closed without merging**
