### PR TITLE
Add MQTT support to climate.py

### PR DESCRIPTION
**Pull request by forfuncsake**
This PR adds support for an MQTT controller to the climate component.

By specifying controller_send_service of mqtt.publish in configuration.yaml
along with supportedController of MQTT in the code file, climate commands
will be published to the topic defined in command_topic.

The included 1520.json file provides hex codes (tested and verified) for
Kelvinator A/C using a R51K/BGE remote with coolix infrared protocol.

### CODE REVIEW

**Comment by smartHomeHub** [comment]
Interesting. Which MQTT controller are you using?
(This PR will have conflicts with the rc branch to be merged tomorrow)

**Comment by forfuncsake** [comment]
I've rolled my own controller on an ESP8266/NodeMCU (not yet shared publicly) that is subscribed to a bunch of topics for various IR and RF (433Mhz) protocols. Depending on which topic the payload arrives on, the controller will emit the code in the payload using the topic protocol.

**Comment by forfuncsake** [comment]
Should I retarget this PR to the `rc` branch, or wait until after it merges and rebase?

**Comment by smartHomeHub** [comment]
Please target the rc branch. The send function was moved to a separate class.
But we really need your controller available for an example of usage.
I think it makes sense to integrate when your controller is ready for real users.

**Comment by forfuncsake** [comment]
I would posit that the "controller" here is ultimately the MQTT broker. Users could run anything they want on the other end of the topic and there are plenty of example projects out there for MQTT clients that emit IR/RF (e.g. https://forum.mysensors.org/topic/8018/mqtt-ir-remote).

However if you really wanted to wait until my specific controller is shared, I could understand.

**Comment by smartHomeHub** [comment]
Aren't the commands in the code file specific to your controller? Describing the controller as MQTT, we give the user the impression that the code files will work with all mqtt controllers.

**Comment by forfuncsake** [comment]
Hmm, I see your point - perhaps it would be best not to include the code file, because ultimately the mqtt message payload would likely be customised by each user, based on their MQTT client...

The codes in my example file are just the hex representation of the data bits using the IR protocol handled by this package: https://github.com/markszabo/IRremoteESP8266/blob/master/src/ir_Coolix.cpp. They are specific to my A/C remote more than the controller itself, however a user would need a client that can appropriately decode and emit the IR.

**Comment by forfuncsake** [comment]
I have added the code changes in a new branch targeting `rc`. 
If you are satisfied with the addition of MQTT support without a specific controller (which is ultimately more flexible), let me know and I will also go ahead with the documentation updates.

**Pull request closed without merging**
