### PR TITLE
Add support for fans with combined power and speed remote buttons

### PR DESCRIPTION
**Pull request by Poeschl**
This PR will add support for IR fans without dedicated speed and combined power buttons.

In my case the remote has 5 buttons (power, speed, oscillation, mode and timer). So I created a additional integration for that type.

To use it the codes file need to define a `speed` command and the `SmartOneSpeedButtonIRFan` gets active. Only the `send_command` method gets overwritten and sends out several `speed` command to get the right speed setting.

The fan is memorizing its speed setting and oscillation state. So if its off and the states on home assistant changes, the changed settings get applied on its turn-on.

### CODE REVIEW

**Comment by Poeschl** [comment]
Found out that there is still an issue during the state restore. Will fix it tomorrow.

**Comment by Poeschl** [comment]
During testing I noticed that the oscillation is not memorized. Is it ignored on purpose or missing?

**Comment by vassilis-panos** [comment]
It is missing. Thanks for mention that.

**Comment by vassilis-panos** [comment]
I need some time for this PR

**Comment by Poeschl** [comment]
Rebased it to the current master

**Comment by Poeschl** [comment]
Any news about the status of this PR?

**Comment by tigers75** [comment]
I have a similar situation, but in my case the states of oscillation and speed are NOT saved by the fan, so it'd be nice if it was possible to  have a  boolean switch (in the json?) so that it checks whether the state is to be saved or not.

**Comment by Poeschl** [comment]
I will rebase it the next days. Still not stale.

**Pull request closed without merging**
