### PR TITLE
Adds support for MSZ-GE22VA

### PR DESCRIPTION
**Pull request by miga97**
Codes for Mitsubishi Electric MSZ-GE22VA Climate

manufacturer: Mitsubishi Electric 
supported Models: MSZ-GE22VA 
commands Encoding: Base64
supported Controller: Broadlink
min Temperature: 16
max Temperature: 31
precision: 1
operation Modes:
 [
    "auto",
    "cool",
    "dry",
    "heat"
]
fan Modes:
[
    "auto",
    "quiet",
    "low",
    "med",
    "high",
    "super high"
]
swing Modes: 
[
    "position 1",
    "position 2",
    "position 3",
    "position 4",
    "position 5",
    "swing",
    "auto"
]

photo of the remote control

photo_2021-01-29_00-13-55

### CODE REVIEW

**Comment by vassilis-panos** [comment]
Wow. It's a lot of work. Awesome

**Comment by miga97** [comment]
> Wow. It's a lot of work. Awesome

thanks, i am not sure of something: dry mode does not have temperature in remote controller so I repeated the same code for all temperatures, is this okay or is there a better way to do it?

**Comment by foudon** [comment]
Hello All and more specifically @miga97.

I would assume that this adds is NOT solely suitable for MSZ-GE22VA but also for the other devices within Mitsubishi Electric product family.
I have a MSZ-GE25VA and the product notice is common with MSZ-GE22VA.

The remove control of my MSZ-GE25VA  looks 100% similar to the picture attached in this section?

What do you think ?
Mtisubishi spilt Family MSZ_GE2 3 4   5

**Comment by miga97** [comment]
Hi @foudon,
I think if the remote is the same, it should almost certainly work.

**Pull request merged**
