### PR TITLE
Add model references to Daikin 1100 codes (FTXS**BVMB and FTXS**CVMB)

### PR DESCRIPTION
**Pull request by ruimarinho**
Add missing model names / references to codes 1100.

### CODE REVIEW

**Comment by smartHomeHub** [comment]
Hi. Thanks for your contribution. Did you also check 3100.json (xiaomi)?

**Comment by ruimarinho** [comment]
3100 is just a conversion from 1100 to Xiaomi format so I would say they are the same reference.

**Comment by smartHomeHub** [comment]
Thanks for your contribution. I really appreciate it.

**Comment by valkjsaaa** [comment]
How do you convert a code from Broadlink to Xiaomi format?

**Pull request merged**
