### PR TITLE
Add support ESPHome remote transmitter as controller

### PR DESCRIPTION
**Pull request by ixkor**
support ESPHome remote transmitter as controller if user-defined service in device config defined like this:
```yml
api:
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'
```

### CODE REVIEW

**Comment by vassilis-panos** [comment]
Very interesting. I will merge it immediately.

**Comment by vassilis-panos** [comment]
Could you rename to 7285.json?
I'm trying to keep the following logic:
1000 - 2999 [Broadlink]
3000 - 4999 [Xiaomi]
5000 - 6999 [LOOKin]
7000 - 8999 [ESPHome]

-- We do not accept MQTT codes.

**Comment by ixkor** [comment]
> Could you rename to 7285.json?
> I'm trying to keep the following logic:
> 1000 - 2999 [Broadlink]
> 3000 - 4999 [Xiaomi]
> 5000 - 6999 [LOOKin]
> 7000 - 8999 [ESPHome]
> 
> -- We do not accept MQTT codes.

Sure, done

**Comment by vassilis-panos** [comment]
Since I'm not familiar with ESPHome, could you explain to me what the value of the controller_data  should be?

**Comment by ixkor** [comment]
> Since I'm not familiar with ESPHome, could you explain to me what the value of the controller_data should be?

For example you have ESPHome device with IR transmitter. Minimal device config:
```yml
esphome:
  name: ir_small # device name
  platform: ESP8266
  board: esp01_1m

api:
  services:
    - service: send_raw_command # service name (device name will be used as prefix)
      variables: # list of service params
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            code: !lambda 'return command;' # use array from service param

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%
```
Then `controller_data` should be `ir_small_send_raw_command` where `ir_small` is a device name, `send_raw_command` - service name.

Example from my HA configuration:
```yml
climate:
  - platform: smartir
    name: Conditioner
    unique_id: living_room_ac
    device_code: 6285
    controller_data: ir_small_send_raw_command
    temperature_sensor: sensor.living_room_temperature
    humidity_sensor: sensor.living_room_humidity
```

**Comment by Ahmed-farag36** [comment]
@ixkor thank you for integrate ESPHome into this beautiful repo, I just wonder how to send code other than raw codes.
for example:
`- remote_transmitter.transmit_nec:
            address: !lambda 'return address;'
            command: !lambda 'return command;'
`
is it right??

**Pull request merged**
