### PR TITLE
Added oscillating support for fan

### PR DESCRIPTION
**Pull request by AS137430**
I added fan oscillating support based on code examples from other fan components in HA

### CODE REVIEW

**Comment by FezVrasta** [comment]
Is there any plan to merge this?

**Comment by smartHomeHub** [comment]
@AS137430 Could you share your JSON file?

**Comment by AS137430** [comment]
```
{
  "manufacturer": "Europace",
  "supportedModels": [
    "Unknown"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "low",
    "medium",
    "high"
  ],
  "commands": {
    "off": "JgBYAAABLJYTEhMTExITExQ2EzgTEhMTEzcUNhQ3EzcUEhITFDYUNxMSFBIUNhQ3ExIUEhQRFDcUNhQ2FBIUERQ3EzcUNhQSFAAFKQABLUkUAAxzAAEsShQADQU=",
    "default": {
      "low": "JgBYAAABLZUTEhMTFBETExM3EzgSExMTEzcTNxQ3EzcUEhITEzcTOBQRFBITExI4ExITExMTEjgUNhM3FDcTEhM4EzcTNxQSEwAFKgABLEoUAAxyAAEtSRQADQU=",
      "medium": "JgBYAAABLZUTEhMTFBETExM3EzgSExMTEzcTNxQ3EzcUEhITEzcTOBQRFBITExI4ExITExMTEjgUNhM3FDcTEhM4EzcTNxQSEwAFKgABLEoUAAxyAAEtSRQADQU=",
      "high": "JgBYAAABLZUTEhMTFBETExM3EzgSExMTEzcTNxQ3EzcUEhITEzcTOBQRFBITExI4ExITExMTEjgUNhM3FDcTEhM4EzcTNxQSEwAFKgABLEoUAAxyAAEtSRQADQU="
    },
    "oscillate": "JgBQAAABLJYTExMSFBITExM3FDYTExMSEzgTNxQ3FDYTExITFDcSOBMTEjgUNhQSExMTEhMTFDYTOBMSFBITNxQ2FDcTNxMTEwAFKwABLEsTAA0FAAAAAAAAAAA="
  }
}
```

**Comment by FezVrasta** [comment]
WTF, stale bot on PRS?

**Comment by mouth4war** [comment]
Would really appreciate a merge on this one before it's winter :)

**Comment by kukudemajia** [comment]
Is there any plan to merge this?

**Comment by smartHomeHub** [comment]
Bump

**Comment by FezVrasta** [comment]
This is not an issue, it's a PR 🤦‍♂️

**Comment by FezVrasta** [comment]
what the actual fuck

**Comment by mouth4war** [comment]
@smarthomehub please merge

**Comment by vassilis-panos** [comment]
Conflicts must be resolved

**Pull request merged**
