### PR TITLE
Exposing hvac_mode to attributes

### PR DESCRIPTION
**Pull request by benquan**
Exposing hvac_mode to attributes as some components in Home Assistant can use it.

### CODE REVIEW

**Comment by smartHomeHub** [comment]
Hello and thank you for your contribution. Can you tell me what components require hvac_mode in the attributes?
Thanks

**Comment by benquan** [comment]
[https://github.com/home-assistant/home-assistant-polymer/issues/3468](url)

The climate history graph has a green shaded area that represents when the HVAC is working. It used to be based on state. But now its based on hvac_action, but it will fall back on hvac_mode when it's not available. Other climate components also expose hvac_mode.

**Comment by smartHomeHub** [comment]
Oh, nice. Thanks for the link

**Comment by benquan** [comment]
Since we do not know what the unit is really doing (only its current operation mode) can we set hvac_action to be equal to havoc_mode? (adding the ...ing of course). Doing this would now solve the history graph issue.

**Comment by benquan** [comment]
All other components have settled on implementing the hvac_action and the issue is solved. can we do the same? [https://github.com/home-assistant/home-assistant/issues/25722#issuecomment-533933632](url)

**Pull request closed without merging**
